---

- name: Install Zabbix-agent
  hosts: nginx
  become: yes

  tasks:
  - name: Get zabbix-agent
    ansible.builtin.get_url:
      url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
      dest: /home/user/

  - name: Install repo zabbix-agent
    apt:
      deb: /home/user/zabbix-release_6.4-1+ubuntu22.04_all.deb

  - name: Update cash
    apt:
      update_cache: yes

  - name: install zabbix-agent
    apt:
      name: zabbix-agent
      state: latest

  - name: stop zabbix-agent
    service:
      name: zabbix-agent.service
      state: stopped

  - name: Copy conf-file
    copy:
      src: /home/user/terraform/yandex/zabbix_agentd.conf
      dest: /etc/zabbix/zabbix_agentd.conf
      mode: 0644
      owner: root
      group: root

  - name: Start zabbix-agent
    service:
      name: zabbix-agent.service
      state: started
 
